# Generated by Django 3.2.5 on 2021-12-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0002_add_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_photos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Gallary/%Y/%m/%d'),
        ),
    ]
