# Generated by Django 3.2.5 on 2021-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0003_alter_add_photos_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_notification', models.CharField(max_length=256)),
                ('photo_notification', models.ImageField(blank=True, null=True, upload_to='notification/%Y/%m/%d')),
                ('notification', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
