# Generated by Django 3.2.5 on 2021-12-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=256)),
                ('lnane', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('mn', models.PositiveBigIntegerField(unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
